#!/bin/sh

coqtop --version > coq-version-used
git hash-object `which coqtop` > coq-githash-used
make clean
make
time coqtop -m -time -batch -R . mindless -impredicative-set -l wavl_noauto.v
time coqtop -m -time -batch -R . mindless -impredicative-set -l wavl.v
time coqtop -m -time -batch -R . mindless -impredicative-set -l wavl_noninter.v
